%module fltk_d

%{
	#include <Fl/Fl.H>
	#include <Fl/Fl_Window.H>
	#include <Fl/Fl_Double_Window.H>
	#include <Fl/Fl_Widget.H>
	#include <Fl/Fl_Button.H>
	#include <Fl/Fl_Group.H>
	#include <Fl/fl_draw.H>
	#include <Fl/Fl_Input_.H>
	#include <Fl/Fl_Input.H>
	#include <Fl/Fl_Pack.H>
	#include <Fl/Fl_Scroll.H>
	#include <Fl/Fl_Scrollbar.H>
	#include <Fl/Fl_Box.H>
	#include <FL/Fl_Color_Chooser.H>
	#include <FL/Fl_Value_Input.H>
	#include <FL/Fl_Value_Output.H>
	#include <Fl/Enumerations.H>
	#include <Fl/Fl_Valuator.H>
	#include <Fl/Fl_Progress.H>
	#include <Fl/Fl_Text_Display.H>
	#include <Fl/Fl_Text_Buffer.H>
	#include <Fl/Fl_Text_Editor.H>
	#include <Fl/Fl_Menu_.H>
	#include <Fl/Fl_Choice.H>
	#include <Fl/Fl_Light_Button.H>
	#include <Fl/Fl_Check_Button.H>
	#include <Fl/Fl_Native_File_Chooser.H>
%}

%rename("%(strip:[Fl_])s") "";

%include "../headers_to_translate/FL/Fl.H"
%include "../headers_to_translate/FL/Fl_Widget.H"
%include "../headers_to_translate/FL/Fl_Button.H"
%include "../headers_to_translate/FL/Fl_Group.H"
%include "../headers_to_translate/FL/Fl_Window.H"
%include "../headers_to_translate/FL/Fl_Double_Window.H"
%include "../headers_to_translate/FL/Fl_Input_.H"
%include "../headers_to_translate/FL/Fl_Input.H"
%include "../headers_to_translate/FL/Fl_Valuator.H"
%include "../headers_to_translate/FL/fl_draw.H"
%include "../headers_to_translate/FL/Enumerations.H"
%include "../headers_to_translate/FL/Fl_Pack.H"
%include "../headers_to_translate/FL/Fl_Scroll.H"
%include "../headers_to_translate/FL/Fl_Scrollbar.H"
%include "../headers_to_translate/FL/Fl_Box.H"
%include "../headers_to_translate/FL/Fl_Color_Chooser.H"
%include "../headers_to_translate/FL/Fl_Value_Input.H"
%include "../headers_to_translate/FL/Fl_Value_Output.H"
%include "../headers_to_translate/FL/Fl_Progress.H"
%include "../headers_to_translate/FL/Fl_Text_Display.H"
%include "../headers_to_translate/FL/Fl_Text_Buffer.H"
%include "../headers_to_translate/FL/Fl_Text_Editor.H"
%include "../headers_to_translate/FL/Fl_Menu_.H"
%include "../headers_to_translate/FL/Fl_Choice.H"
%include "../headers_to_translate/FL/Fl_Light_Button.H"
%include "../headers_to_translate/FL/Fl_Check_Button.H"
%include "../headers_to_translate/FL/Fl_Native_File_Chooser.H"
